// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iounvptlpsidiaseouzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvdW52cHRscHNpZGlhc2VvdXpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDk0NDYsImV4cCI6MjA3NDYyNTQ0Nn0.x9AlufHJ0vj3ByzRRcwaJbZRFUUd1grEOKCiUEyztes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});